# Generated by Django 5.2.17 on 2026-08-15 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='assignment',
            new_name='assignments_course__eda10d_idx',
            old_name='assignment_course_pub_idx',
        ),
        migrations.RenameIndex(
            model_name='submission',
            new_name='assignments_assignm_20337d_idx',
            old_name='submission_assignment_idx',
        ),
        migrations.RenameIndex(
            model_name='submission',
            new_name='assignments_student_548dfb_idx',
            old_name='submission_student_idx',
        ),
    ]
