# Generated by Django 5.2.17 on 2026-08-13 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('order_created', 'Order Created'), ('payment_verified', 'Payment Verified'), ('order_approved', 'Order Approved'), ('order_rejected', 'Order Rejected'), ('order_cancelled', 'Order Cancelled'), ('enrollment_created', 'Enrollment Created'), ('lesson_completed', 'Lesson Completed'), ('course_completed', 'Course Completed'), ('certificate_issued', 'Certificate Issued'), ('course_published', 'Course Published'), ('course_updated', 'Course Updated'), ('new_review', 'New Review')], db_index=True, max_length=50),
        ),
    ]
