# Generated by Django 5.2.17 on 2026-08-15 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attempt',
            options={'ordering': ['-started_at']},
        ),
        migrations.AlterModelOptions(
            name='option',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['order']},
        ),
        migrations.RenameIndex(
            model_name='attempt',
            new_name='quizzes_att_student_e4599a_idx',
            old_name='attempt_student_quiz_idx',
        ),
        migrations.RenameIndex(
            model_name='quiz',
            new_name='quizzes_qui_course__62ace5_idx',
            old_name='quiz_course_pub_idx',
        ),
        migrations.AlterField(
            model_name='quiz',
            name='time_limit_minutes',
            field=models.PositiveIntegerField(default=0, help_text='0 means no time limit.'),
        ),
    ]
