# Generated by Django 5.2.17 on 2026-08-05 07:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursefeature',
            options={'ordering': ['id'], 'verbose_name': 'Course Feature', 'verbose_name_plural': 'Course Features'},
        ),
        migrations.AlterModelOptions(
            name='learningoutcome',
            options={'ordering': ['id'], 'verbose_name': 'Learning Outcome', 'verbose_name_plural': 'Learning Outcomes'},
        ),
        migrations.AlterModelOptions(
            name='requirement',
            options={'ordering': ['id'], 'verbose_name': 'Requirement', 'verbose_name_plural': 'Requirements'},
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_published', models.BooleanField(db_index=True, default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='courses.course')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('video_url', models.URLField(blank=True)),
                ('duration', models.PositiveIntegerField(default=0, help_text='Duration in seconds.')),
                ('order', models.PositiveIntegerField(default=1)),
                ('is_preview', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_published', models.BooleanField(db_index=True, default=False)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lectures', to='courses.section')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(blank=True, null=True, upload_to='courses/resources/')),
                ('external_url', models.URLField(blank=True)),
                ('resource_type', models.CharField(choices=[('pdf', 'PDF'), ('document', 'Document'), ('zip', 'ZIP Archive'), ('image', 'Image'), ('video', 'Video'), ('link', 'External Link'), ('other', 'Other')], default='pdf', max_length=20)),
                ('order', models.PositiveIntegerField(default=1)),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='courses.lecture')),
            ],
            options={
                'ordering': ['order'],
                'indexes': [models.Index(fields=['lecture', 'order'], name='courses_res_lecture_3b6e05_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='section',
            index=models.Index(fields=['course', 'order'], name='courses_sec_course__60bff3_idx'),
        ),
        migrations.AddIndex(
            model_name='section',
            index=models.Index(fields=['slug'], name='courses_sec_slug_c6a512_idx'),
        ),
        migrations.AddConstraint(
            model_name='section',
            constraint=models.UniqueConstraint(fields=('course', 'order'), name='unique_section_order_per_course'),
        ),
        migrations.AddIndex(
            model_name='lecture',
            index=models.Index(fields=['section', 'order'], name='courses_lec_section_bfe9bf_idx'),
        ),
        migrations.AddConstraint(
            model_name='lecture',
            constraint=models.UniqueConstraint(fields=('section', 'order'), name='unique_lecture_order_per_section'),
        ),
    ]
