# Generated by Django 5.2.17 on 2026-08-06 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_coursefeature_options_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='resource',
            name='courses_res_lecture_3b6e05_idx',
        ),
        migrations.AddField(
            model_name='resource',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddConstraint(
            model_name='lecture',
            constraint=models.UniqueConstraint(fields=('section', 'title'), name='unique_lecture_title_per_section'),
        ),
        migrations.AddConstraint(
            model_name='section',
            constraint=models.UniqueConstraint(fields=('course', 'title'), name='unique_section_title_per_course'),
        ),
    ]
