MAX_CATEGORY_NAME_LENGTH = 100
MAX_CATEGORY_DESCRIPTION_LENGTH = 500

MAX_COURSE_TITLE_LENGTH = 255
MAX_COURSE_SUBTITLE_LENGTH = 255

MAX_FEATURE_LENGTH = 255
MAX_REQUIREMENT_LENGTH = 255
MAX_LEARNING_OUTCOME_LENGTH = 255

DEFAULT_COURSE_LANGUAGE = "english"
DEFAULT_COURSE_LEVEL = "beginner"
DEFAULT_COURSE_STATUS = "draft"

MAX_PRICE_DIGITS = 10
PRICE_DECIMAL_PLACES = 2

MAX_SLUG_LENGTH = 255